
server:
  port: 8081
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://10.8.0.1:3306/study
    username: study
    password:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
